wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.10
    cli_version: 0.15.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1688980335.088239
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 12
      - 41
      - 53
      - 55
      - 80
      2:
      - 1
      - 2
      - 3
      - 5
      - 12
      - 41
      - 53
      - 55
      - 80
      3:
      - 13
      - 23
      4: 3.10.10
      5: 0.15.0
      8:
      - 5
