name: frcnn
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - absl-py=1.4.0=pyhd8ed1ab_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - async-timeout=4.0.2=pyhd8ed1ab_0
  - attrs=23.1.0=pyh71513ae_1
  - blinker=1.6.2=pyhd8ed1ab_0
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.19.1=hd590300_0
  - ca-certificates=2023.5.7=hbcca054_0
  - cachetools=5.3.1=pyhd8ed1ab_0
  - charset-normalizer=3.1.0=pyhd8ed1ab_0
  - curl=8.1.2=h409715c_0
  - gettext=0.21.1=h27087fc_0
  - git=2.41.0=pl5321h86e50cf_0
  - google-auth=2.21.0=pyh1a96a4e_0
  - google-auth-oauthlib=1.0.0=pyhd8ed1ab_1
  - idna=3.4=pyhd8ed1ab_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.20.1=h81ceb04_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - libabseil=20230125.3=cxx17_h59595ed_0
  - libblas=3.9.0=17_linux64_openblas
  - libcblas=3.9.0=17_linux64_openblas
  - libcurl=8.1.2=h409715c_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.2.0=h65d4601_19
  - libgfortran-ng=13.1.0=h69a702a_0
  - libgfortran5=13.1.0=h15d22d2_0
  - libgomp=12.2.0=h65d4601_19
  - libgrpc=1.56.0=h3905398_2
  - libiconv=1.17=h166bdaf_0
  - liblapack=3.9.0=17_linux64_openblas
  - libnghttp2=1.52.0=h61bc06f_0
  - libnsl=2.0.0=h7f98852_0
  - libopenblas=0.3.23=pthreads_h80387f5_0
  - libprotobuf=4.23.3=hd1fb520_0
  - libsqlite=3.41.2=h2797004_1
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-ng=13.1.0=hfd8a6a1_0
  - libuuid=2.38.1=h0b41bf4_0
  - libzlib=1.2.13=h166bdaf_4
  - markdown=3.4.3=pyhd8ed1ab_0
  - ncurses=6.3=h27087fc_1
  - oauthlib=3.2.2=pyhd8ed1ab_0
  - openssl=3.1.1=hd590300_1
  - pcre2=10.40=hc3806b6_0
  - perl=5.32.1=2_h7f98852_perl5
  - pip=23.1.2=pyhd8ed1ab_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pyjwt=2.7.0=pyhd8ed1ab_0
  - pyopenssl=23.2.0=pyhd8ed1ab_1
  - python=3.10.10=he550d4f_0_cpython
  - python_abi=3.10=3_cp310
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - re2=2023.03.02=h8c504da_0
  - readline=8.2=h8228510_1
  - requests=2.31.0=pyhd8ed1ab_0
  - requests-oauthlib=1.3.1=pyhd8ed1ab_0
  - rsa=4.9=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - tensorboard=2.13.0=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - typing-extensions=4.7.1=hd8ed1ab_0
  - typing_extensions=4.7.1=pyha770c72_0
  - tzdata=2023c=h71feb2d_0
  - urllib3=1.26.15=pyhd8ed1ab_0
  - werkzeug=2.3.6=pyhd8ed1ab_0
  - wheel=0.40.0=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - zipp=3.15.0=pyhd8ed1ab_0
  - zstd=1.5.2=h3eb15da_6
  - pip:
    - adal==1.2.7
    - aiohttp==3.8.4
    - aiohttp-retry==2.8.3
    - aiokafka==0.8.1
    - aiosqlite==0.19.0
    - alembic==1.11.1
    - amqp==5.1.1
    - antlr4-python3-runtime==4.9.3
    - apprise==1.4.0
    - argcomplete==2.1.2
    - asgi-lifespan==2.1.0
    - asyncpg==0.27.0
    - asyncssh==2.13.2
    - atpublic==4.0
    - azure-common==1.1.28
    - azure-graphrbac==0.61.1
    - azure-mgmt-authorization==3.0.0
    - azure-mgmt-containerregistry==10.1.0
    - azure-mgmt-core==1.4.0
    - azure-mgmt-keyvault==10.2.2
    - azure-mgmt-resource==22.0.0
    - azure-mgmt-storage==21.0.0
    - azureml-core==1.52.0
    - babel==2.12.1
    - backports-tempfile==1.0
    - backports-weakref==1.0.post1
    - bcrypt==4.0.1
    - billiard==4.1.0
    - brotli==1.0.9
    - brotlipy==0.7.0
    - celery==5.3.1
    - certifi==2023.5.7
    - cffi==1.15.1
    - click==8.1.3
    - click-didyoumean==0.3.0
    - click-plugins==1.1.1
    - click-repl==0.3.0
    - colabcode==0.3.0
    - colorama==0.4.6
    - coolname==2.2.0
    - croniter==1.4.1
    - cryptography==41.0.1
    - databricks-cli==0.17.7
    - dateparser==1.1.8
    - deepaas==2.1.0
    - dictdiffer==0.9.0
    - diskcache==5.6.1
    - distlib==0.3.6
    - distro==1.8.0
    - dpath==2.1.6
    - dulwich==0.21.5
    - dvc==3.3.1
    - dvc-data==2.3.3
    - dvc-http==2.30.2
    - dvc-objects==0.23.0
    - dvc-render==0.5.3
    - dvc-studio-client==0.10.0
    - dvc-task==0.3.0
    - dvc-webdav==2.19.1
    - fastapi==0.99.1
    - filelock==3.12.0
    - flatten-dict==0.4.2
    - flufl-lock==7.1.1
    - frozenlist==1.3.3
    - funcy==2.0
    - gevent==22.10.2
    - geventhttpclient==2.0.2
    - grandalf==0.8
    - greenlet==2.0.2
    - griffe==0.30.1
    - grpcio==1.56.0
    - gunicorn==20.1.0
    - h2==4.1.0
    - hpack==4.0.0
    - humanfriendly==10.0
    - hydra-core==1.3.2
    - hyperframe==6.0.1
    - importlib-metadata==6.6.0
    - iterative-telemetry==0.0.8
    - jeepney==0.8.0
    - json5==0.9.14
    - jsonpatch==1.33
    - jsonpickle==3.0.1
    - jsonschema==4.17.3
    - jupyter-server==1.24.0
    - jupyterlab==3.0.7
    - jupyterlab-server==2.23.0
    - kafka-python==2.0.2
    - knack==0.10.1
    - kombu==5.3.1
    - kubernetes==26.1.0
    - mako==1.2.4
    - markupsafe==2.1.3
    - mlflow==2.3.2
    - mlserver==1.3.4
    - mlserver-mlflow==1.3.4
    - msal==1.22.0
    - msal-extensions==1.0.0
    - msrest==0.7.1
    - msrestazure==0.6.4
    - multidict==6.0.4
    - nanotime==0.5.2
    - nbclassic==0.3.7
    - ndg-httpsclient==0.5.1
    - nest-asyncio==1.4.3
    - netifaces==0.11.0
    - notebook==6.4.5
    - numpy==1.25.0
    - omegaconf==2.3.0
    - paramiko==3.2.0
    - pathspec==0.11.1
    - pendulum==2.1.2
    - pexpect==4.8.0
    - pkginfo==1.9.6
    - platformdirs==3.5.1
    - prefect==2.10.18
    - prometheus-flask-exporter==0.22.4
    - protobuf==4.23.3
    - ptyprocess==0.7.0
    - py-grpc-prometheus==0.7.0
    - pydantic==1.10.10
    - pygit2==1.12.2
    - pygtrie==2.5.0
    - pynacl==1.5.0
    - pyngrok==6.0.0
    - pyparsing==3.0.9
    - pysftp==0.2.9
    - pysocks==1.7.1
    - pytest==7.3.1
    - python-rapidjson==1.10
    - pytzdata==2020.1
    - querystring-parser==1.2.4
    - readchar==4.0.5
    - requests-auth-aws-sigv4==0.7
    - ruamel-yaml==0.17.32
    - ruamel-yaml-clib==0.2.7
    - scmrepo==1.0.4
    - secretstorage==3.3.3
    - setuptools==59.5.0
    - shortuuid==1.0.11
    - shtab==1.6.2
    - sqlalchemy==2.0.17
    - sqltrie==0.7.0
    - starlette==0.27.0
    - starlette-exporter==0.16.0
    - tensorboard-data-server==0.7.0
    - tomlkit==0.11.8
    - torch==1.12.0
    - torchvision==0.13.0
    - tritonclient==2.35.0
    - typer==0.9.0
    - uvicorn==0.22.0
    - uvloop==0.17.0
    - vine==5.0.0
    - virtualenv==20.23.1
    - voluptuous==0.13.1
    - yarl==1.9.2
    - zc-lockfile==3.0.post1
    - zope-event==5.0
    - zope-interface==6.0
prefix: /home/se1131/anaconda3/envs/frcnn

